### ISSUE TITLE
API

### ISSUE THREAD

**Issue by alexichepura** [spiral/sf.js#19]
In order to release beta, we need to stabilise API.
API has to be clear, short and memorable.
Here is my suggestions. Let's discuss.

1) functions used in instances
sf.registerInstanceType = (Instance, "js-sf-instance") => {...}
sf.modulePrototype() = () => Object.create(sf.modules.core.BaseDOMConstructor.prototype

2) functions in instancesController but need shortcut for manual instances control
sf.addInstance = (instanceName, node, options) => {...}
sf.removeInstance = (instanceName, node) => {...}
sf.getInstance = (instanceName, node) => {...}
sf.getInstances = (instanceName) => {...} //(new) instanceName is optional

3) variables naming
Instance.prototype.optionsToGrab -> Instance.prototype.grab

PS 
sf.getInstance - I would love if I can pass only node as parameter. It would be easier to debug.
And we've never user the same node for 2 different instances.
I know, there would be more calculations, but very useful for debug.

**Comment by ZmicerBoksha** [comment]
https://github.com/sfjs/sf.js/commit/dd4f6de765b75162cdcec68da483dfcddbb5bdbd

**Comment by alexichepura** [comment]
Looks good for me.
