### ISSUE TITLE
Add globalOverwrites?

### ISSUE THREAD

**Issue by Systerr** [spiral/sf.js#2]
This feature needed if we want to overwrite some default values. For example we want to grab additional attributesToGrab.
Maybe like this.

```
spiralFrontend.globalOverwrites = {
    instances: {//type
        Form:{
            attributesToGrab:{
                "action2": {
                    "key": "url",
                    "value": "/"
                }
            }
        }

    }
}
```

Or maybe for change default classes

**Comment by Systerr** [comment]
I think that for usage like described we should use inheritance.
If any one have suggestion  please write it.

**Comment by alexichepura** [comment]
we came up to the idea of placing variable before sf.js runs.

```
var sf = {
  defaultOptions: {
    instances: {
      form: {
        messagesType: "spiral"
      }
    }
  }
}
```

So the sequence to gather options:
0) defaultOptions from instance itself (if need and provided by the instance itself)
1) sf.defaultOptions
2) data-options - should accept JSON string or variable name
3) optionsToGrab

**Comment by alexichepura** [comment]
Implemented.
data-options is in #4
